services:
  - type: web
    name: iitbtask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "PYTHONPATH=$PYTHONPATH:/opt/render/project/src gunicorn iitbtask.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "iitbtask.settings"
      - key: PYTHON_VERSION
        value: "3.11"
    plan: free
    build:
      env:
        PYTHON_VERSION: 3.11
    workingDirectory: ./  # Specify if project is not at the root, adjust as per your project
